// Comprehensive ISO 3166-1 country list with dial codes, flag emojis,
// and bilingual (FR / EN) display names. Kept in a separate file so
// lib/phoneValidation.ts can stay focused on logic + types.
//
// Order in this file is alphabetical by English name. The PhoneInput
// dropdown re-sorts at render time per the current locale, so the
// order here is just for source-code readability.
//
// The 5 platform countries (CM/CI/SN/TG/BJ) carry their strict
// validation metadata (localLength + prefixes + placeholder +
// groupSizes). Everyone else uses the loose 6-15-digit envelope
// validated in phoneValidation.ts.

export interface CountryMeta {
  iso:          string        // ISO 3166-1 alpha-2
  name:         string        // English name (used for search + EN sort)
  nameFr:       string        // French name (used for FR sort + display)
  flag:         string
  code:         string        // "+33"
  dialCode:     string        // "33"
  // Strict validation only fires when localLength > 0. Non-platform
  // countries set localLength=0 and rely on the loose 6-15-digit
  // range check in validateLocalPhone.
  localLength:  number
  prefixes:     string[]
  placeholder:  string
  groupSizes:   number[]
}

// Compact factory for the ~240 non-platform countries.
function c(iso: string, code: string, name: string, nameFr: string, flag: string): CountryMeta {
  return {
    iso, code, dialCode: code.replace(/^\+/, ''),
    name, nameFr, flag,
    localLength: 0, prefixes: [],
    placeholder: 'XXX XXX XXX', groupSizes: [3, 3, 3],
  }
}

export const COUNTRIES_DATA: CountryMeta[] = [
  c('AF', '+93',   'Afghanistan',          'Afghanistan',                  '🇦🇫'),
  c('AL', '+355',  'Albania',              'Albanie',                      '🇦🇱'),
  c('DZ', '+213',  'Algeria',              'Algérie',                      '🇩🇿'),
  c('AD', '+376',  'Andorra',              'Andorre',                      '🇦🇩'),
  c('AO', '+244',  'Angola',               'Angola',                       '🇦🇴'),
  c('AG', '+1268', 'Antigua and Barbuda',  'Antigua-et-Barbuda',           '🇦🇬'),
  c('AR', '+54',   'Argentina',            'Argentine',                    '🇦🇷'),
  c('AM', '+374',  'Armenia',              'Arménie',                      '🇦🇲'),
  c('AU', '+61',   'Australia',            'Australie',                    '🇦🇺'),
  c('AT', '+43',   'Austria',              'Autriche',                     '🇦🇹'),
  c('AZ', '+994',  'Azerbaijan',           'Azerbaïdjan',                  '🇦🇿'),
  c('BS', '+1242', 'Bahamas',              'Bahamas',                      '🇧🇸'),
  c('BH', '+973',  'Bahrain',              'Bahreïn',                      '🇧🇭'),
  c('BD', '+880',  'Bangladesh',           'Bangladesh',                   '🇧🇩'),
  c('BB', '+1246', 'Barbados',             'Barbade',                      '🇧🇧'),
  c('BY', '+375',  'Belarus',              'Biélorussie',                  '🇧🇾'),
  c('BE', '+32',   'Belgium',              'Belgique',                     '🇧🇪'),
  c('BZ', '+501',  'Belize',               'Belize',                       '🇧🇿'),
  // Benin — platform country (BJ); strict validation
  {
    iso: 'BJ', code: '+229', dialCode: '229',
    name: 'Benin', nameFr: 'Bénin', flag: '🇧🇯',
    localLength: 8, prefixes: ['94', '95', '96', '97'],
    placeholder: 'XX XX XX XX', groupSizes: [2, 2, 2, 2],
  },
  c('BT', '+975',  'Bhutan',                'Bhoutan',                     '🇧🇹'),
  c('BO', '+591',  'Bolivia',               'Bolivie',                     '🇧🇴'),
  c('BA', '+387',  'Bosnia and Herzegovina','Bosnie-Herzégovine',          '🇧🇦'),
  c('BW', '+267',  'Botswana',              'Botswana',                    '🇧🇼'),
  c('BR', '+55',   'Brazil',                'Brésil',                      '🇧🇷'),
  c('BN', '+673',  'Brunei',                'Brunei',                      '🇧🇳'),
  c('BG', '+359',  'Bulgaria',              'Bulgarie',                    '🇧🇬'),
  c('BF', '+226',  'Burkina Faso',          'Burkina Faso',                '🇧🇫'),
  c('BI', '+257',  'Burundi',               'Burundi',                     '🇧🇮'),
  c('KH', '+855',  'Cambodia',              'Cambodge',                    '🇰🇭'),
  // Cameroon — platform country (CM); strict validation
  {
    iso: 'CM', code: '+237', dialCode: '237',
    name: 'Cameroon', nameFr: 'Cameroun', flag: '🇨🇲',
    localLength: 9, prefixes: ['65', '67', '68', '69'],
    placeholder: '6XX XXX XXX', groupSizes: [3, 3, 3],
  },
  c('CA', '+1',    'Canada',                'Canada',                      '🇨🇦'),
  c('CV', '+238',  'Cape Verde',            'Cap-Vert',                    '🇨🇻'),
  c('CF', '+236',  'Central African Republic','République centrafricaine', '🇨🇫'),
  c('TD', '+235',  'Chad',                  'Tchad',                       '🇹🇩'),
  c('CL', '+56',   'Chile',                 'Chili',                       '🇨🇱'),
  c('CN', '+86',   'China',                 'Chine',                       '🇨🇳'),
  c('CO', '+57',   'Colombia',              'Colombie',                    '🇨🇴'),
  c('KM', '+269',  'Comoros',               'Comores',                     '🇰🇲'),
  c('CG', '+242',  'Congo',                 'Congo',                       '🇨🇬'),
  c('CR', '+506',  'Costa Rica',            'Costa Rica',                  '🇨🇷'),
  // Côte d'Ivoire — platform country (CI); strict validation
  {
    iso: 'CI', code: '+225', dialCode: '225',
    name: "Côte d'Ivoire", nameFr: "Côte d'Ivoire", flag: '🇨🇮',
    localLength: 10, prefixes: ['01', '05', '06', '07', '08', '09'],
    placeholder: 'XX XX XX XX XX', groupSizes: [2, 2, 2, 2, 2],
  },
  c('HR', '+385',  'Croatia',               'Croatie',                     '🇭🇷'),
  c('CU', '+53',   'Cuba',                  'Cuba',                        '🇨🇺'),
  c('CY', '+357',  'Cyprus',                'Chypre',                      '🇨🇾'),
  c('CZ', '+420',  'Czech Republic',        'Tchéquie',                    '🇨🇿'),
  c('CD', '+243',  'DRC',                   'RD Congo',                    '🇨🇩'),
  c('DK', '+45',   'Denmark',               'Danemark',                    '🇩🇰'),
  c('DJ', '+253',  'Djibouti',              'Djibouti',                    '🇩🇯'),
  c('DM', '+1767', 'Dominica',              'Dominique',                   '🇩🇲'),
  c('DO', '+1809', 'Dominican Republic',    'République dominicaine',      '🇩🇴'),
  c('EC', '+593',  'Ecuador',               'Équateur',                    '🇪🇨'),
  c('EG', '+20',   'Egypt',                 'Égypte',                      '🇪🇬'),
  c('SV', '+503',  'El Salvador',           'Salvador',                    '🇸🇻'),
  c('GQ', '+240',  'Equatorial Guinea',     'Guinée équatoriale',          '🇬🇶'),
  c('ER', '+291',  'Eritrea',               'Érythrée',                    '🇪🇷'),
  c('EE', '+372',  'Estonia',               'Estonie',                     '🇪🇪'),
  c('SZ', '+268',  'Eswatini',              'Eswatini',                    '🇸🇿'),
  c('ET', '+251',  'Ethiopia',              'Éthiopie',                    '🇪🇹'),
  c('FJ', '+679',  'Fiji',                  'Fidji',                       '🇫🇯'),
  c('FI', '+358',  'Finland',               'Finlande',                    '🇫🇮'),
  c('FR', '+33',   'France',                'France',                      '🇫🇷'),
  c('GA', '+241',  'Gabon',                 'Gabon',                       '🇬🇦'),
  c('GM', '+220',  'Gambia',                'Gambie',                      '🇬🇲'),
  c('GE', '+995',  'Georgia',               'Géorgie',                     '🇬🇪'),
  c('DE', '+49',   'Germany',               'Allemagne',                   '🇩🇪'),
  c('GH', '+233',  'Ghana',                 'Ghana',                       '🇬🇭'),
  c('GR', '+30',   'Greece',                'Grèce',                       '🇬🇷'),
  c('GD', '+1473', 'Grenada',               'Grenade',                     '🇬🇩'),
  c('GT', '+502',  'Guatemala',             'Guatemala',                   '🇬🇹'),
  c('GN', '+224',  'Guinea',                'Guinée',                      '🇬🇳'),
  c('GW', '+245',  'Guinea-Bissau',         'Guinée-Bissau',               '🇬🇼'),
  c('GY', '+592',  'Guyana',                'Guyana',                      '🇬🇾'),
  c('HT', '+509',  'Haiti',                 'Haïti',                       '🇭🇹'),
  c('HN', '+504',  'Honduras',              'Honduras',                    '🇭🇳'),
  c('HK', '+852',  'Hong Kong',             'Hong Kong',                   '🇭🇰'),
  c('HU', '+36',   'Hungary',               'Hongrie',                     '🇭🇺'),
  c('IS', '+354',  'Iceland',               'Islande',                     '🇮🇸'),
  c('IN', '+91',   'India',                 'Inde',                        '🇮🇳'),
  c('ID', '+62',   'Indonesia',             'Indonésie',                   '🇮🇩'),
  c('IR', '+98',   'Iran',                  'Iran',                        '🇮🇷'),
  c('IQ', '+964',  'Iraq',                  'Irak',                        '🇮🇶'),
  c('IE', '+353',  'Ireland',               'Irlande',                     '🇮🇪'),
  c('IL', '+972',  'Israel',                'Israël',                      '🇮🇱'),
  c('IT', '+39',   'Italy',                 'Italie',                      '🇮🇹'),
  c('JM', '+1876', 'Jamaica',               'Jamaïque',                    '🇯🇲'),
  c('JP', '+81',   'Japan',                 'Japon',                       '🇯🇵'),
  c('JO', '+962',  'Jordan',                'Jordanie',                    '🇯🇴'),
  c('KZ', '+7',    'Kazakhstan',            'Kazakhstan',                  '🇰🇿'),
  c('KE', '+254',  'Kenya',                 'Kenya',                       '🇰🇪'),
  c('KI', '+686',  'Kiribati',              'Kiribati',                    '🇰🇮'),
  c('KW', '+965',  'Kuwait',                'Koweït',                      '🇰🇼'),
  c('KG', '+996',  'Kyrgyzstan',            'Kirghizistan',                '🇰🇬'),
  c('LA', '+856',  'Laos',                  'Laos',                        '🇱🇦'),
  c('LV', '+371',  'Latvia',                'Lettonie',                    '🇱🇻'),
  c('LB', '+961',  'Lebanon',               'Liban',                       '🇱🇧'),
  c('LS', '+266',  'Lesotho',               'Lesotho',                     '🇱🇸'),
  c('LR', '+231',  'Liberia',               'Libéria',                     '🇱🇷'),
  c('LY', '+218',  'Libya',                 'Libye',                       '🇱🇾'),
  c('LI', '+423',  'Liechtenstein',         'Liechtenstein',               '🇱🇮'),
  c('LT', '+370',  'Lithuania',             'Lituanie',                    '🇱🇹'),
  c('LU', '+352',  'Luxembourg',            'Luxembourg',                  '🇱🇺'),
  c('MO', '+853',  'Macau',                 'Macao',                       '🇲🇴'),
  c('MG', '+261',  'Madagascar',            'Madagascar',                  '🇲🇬'),
  c('MW', '+265',  'Malawi',                'Malawi',                      '🇲🇼'),
  c('MY', '+60',   'Malaysia',              'Malaisie',                    '🇲🇾'),
  c('MV', '+960',  'Maldives',              'Maldives',                    '🇲🇻'),
  c('ML', '+223',  'Mali',                  'Mali',                        '🇲🇱'),
  c('MT', '+356',  'Malta',                 'Malte',                       '🇲🇹'),
  c('MH', '+692',  'Marshall Islands',      'Îles Marshall',               '🇲🇭'),
  c('MR', '+222',  'Mauritania',            'Mauritanie',                  '🇲🇷'),
  c('MU', '+230',  'Mauritius',             'Maurice',                     '🇲🇺'),
  c('MX', '+52',   'Mexico',                'Mexique',                     '🇲🇽'),
  c('FM', '+691',  'Micronesia',            'Micronésie',                  '🇫🇲'),
  c('MD', '+373',  'Moldova',               'Moldavie',                    '🇲🇩'),
  c('MC', '+377',  'Monaco',                'Monaco',                      '🇲🇨'),
  c('MN', '+976',  'Mongolia',              'Mongolie',                    '🇲🇳'),
  c('ME', '+382',  'Montenegro',            'Monténégro',                  '🇲🇪'),
  c('MA', '+212',  'Morocco',               'Maroc',                       '🇲🇦'),
  c('MZ', '+258',  'Mozambique',            'Mozambique',                  '🇲🇿'),
  c('MM', '+95',   'Myanmar',               'Birmanie',                    '🇲🇲'),
  c('NA', '+264',  'Namibia',               'Namibie',                     '🇳🇦'),
  c('NR', '+674',  'Nauru',                 'Nauru',                       '🇳🇷'),
  c('NP', '+977',  'Nepal',                 'Népal',                       '🇳🇵'),
  c('NL', '+31',   'Netherlands',           'Pays-Bas',                    '🇳🇱'),
  c('NZ', '+64',   'New Zealand',           'Nouvelle-Zélande',            '🇳🇿'),
  c('NI', '+505',  'Nicaragua',             'Nicaragua',                   '🇳🇮'),
  c('NE', '+227',  'Niger',                 'Niger',                       '🇳🇪'),
  c('NG', '+234',  'Nigeria',               'Nigéria',                     '🇳🇬'),
  c('KP', '+850',  'North Korea',           'Corée du Nord',               '🇰🇵'),
  c('MK', '+389',  'North Macedonia',       'Macédoine du Nord',           '🇲🇰'),
  c('NO', '+47',   'Norway',                'Norvège',                     '🇳🇴'),
  c('OM', '+968',  'Oman',                  'Oman',                        '🇴🇲'),
  c('PK', '+92',   'Pakistan',              'Pakistan',                    '🇵🇰'),
  c('PW', '+680',  'Palau',                 'Palaos',                      '🇵🇼'),
  c('PS', '+970',  'Palestine',             'Palestine',                   '🇵🇸'),
  c('PA', '+507',  'Panama',                'Panama',                      '🇵🇦'),
  c('PG', '+675',  'Papua New Guinea',      'Papouasie-Nouvelle-Guinée',   '🇵🇬'),
  c('PY', '+595',  'Paraguay',              'Paraguay',                    '🇵🇾'),
  c('PE', '+51',   'Peru',                  'Pérou',                       '🇵🇪'),
  c('PH', '+63',   'Philippines',           'Philippines',                 '🇵🇭'),
  c('PL', '+48',   'Poland',                'Pologne',                     '🇵🇱'),
  c('PT', '+351',  'Portugal',              'Portugal',                    '🇵🇹'),
  c('QA', '+974',  'Qatar',                 'Qatar',                       '🇶🇦'),
  c('RO', '+40',   'Romania',               'Roumanie',                    '🇷🇴'),
  c('RU', '+7',    'Russia',                'Russie',                      '🇷🇺'),
  c('RW', '+250',  'Rwanda',                'Rwanda',                      '🇷🇼'),
  c('KN', '+1869', 'Saint Kitts and Nevis', 'Saint-Christophe-et-Niévès',  '🇰🇳'),
  c('LC', '+1758', 'Saint Lucia',           'Sainte-Lucie',                '🇱🇨'),
  c('VC', '+1784', 'Saint Vincent and the Grenadines', 'Saint-Vincent-et-les-Grenadines', '🇻🇨'),
  c('WS', '+685',  'Samoa',                 'Samoa',                       '🇼🇸'),
  c('SM', '+378',  'San Marino',            'Saint-Marin',                 '🇸🇲'),
  c('ST', '+239',  'São Tomé and Príncipe', 'São Tomé-et-Príncipe',        '🇸🇹'),
  c('SA', '+966',  'Saudi Arabia',          'Arabie saoudite',             '🇸🇦'),
  // Senegal — platform country (SN); strict validation
  {
    iso: 'SN', code: '+221', dialCode: '221',
    name: 'Senegal', nameFr: 'Sénégal', flag: '🇸🇳',
    localLength: 9, prefixes: ['76', '77', '78'],
    placeholder: '7X XXX XX XX', groupSizes: [2, 3, 2, 2],
  },
  c('RS', '+381',  'Serbia',                'Serbie',                      '🇷🇸'),
  c('SC', '+248',  'Seychelles',            'Seychelles',                  '🇸🇨'),
  c('SL', '+232',  'Sierra Leone',          'Sierra Leone',                '🇸🇱'),
  c('SG', '+65',   'Singapore',             'Singapour',                   '🇸🇬'),
  c('SK', '+421',  'Slovakia',              'Slovaquie',                   '🇸🇰'),
  c('SI', '+386',  'Slovenia',              'Slovénie',                    '🇸🇮'),
  c('SB', '+677',  'Solomon Islands',       'Îles Salomon',                '🇸🇧'),
  c('SO', '+252',  'Somalia',               'Somalie',                     '🇸🇴'),
  c('ZA', '+27',   'South Africa',          'Afrique du Sud',              '🇿🇦'),
  c('KR', '+82',   'South Korea',           'Corée du Sud',                '🇰🇷'),
  c('SS', '+211',  'South Sudan',           'Soudan du Sud',               '🇸🇸'),
  c('ES', '+34',   'Spain',                 'Espagne',                     '🇪🇸'),
  c('LK', '+94',   'Sri Lanka',             'Sri Lanka',                   '🇱🇰'),
  c('SD', '+249',  'Sudan',                 'Soudan',                      '🇸🇩'),
  c('SR', '+597',  'Suriname',              'Suriname',                    '🇸🇷'),
  c('SE', '+46',   'Sweden',                'Suède',                       '🇸🇪'),
  c('CH', '+41',   'Switzerland',           'Suisse',                      '🇨🇭'),
  c('SY', '+963',  'Syria',                 'Syrie',                       '🇸🇾'),
  c('TW', '+886',  'Taiwan',                'Taïwan',                      '🇹🇼'),
  c('TJ', '+992',  'Tajikistan',            'Tadjikistan',                 '🇹🇯'),
  c('TZ', '+255',  'Tanzania',              'Tanzanie',                    '🇹🇿'),
  c('TH', '+66',   'Thailand',              'Thaïlande',                   '🇹🇭'),
  c('TL', '+670',  'Timor-Leste',           'Timor oriental',              '🇹🇱'),
  // Togo — platform country (TG); strict validation
  {
    iso: 'TG', code: '+228', dialCode: '228',
    name: 'Togo', nameFr: 'Togo', flag: '🇹🇬',
    localLength: 8, prefixes: ['9'],
    placeholder: '9X XX XX XX', groupSizes: [2, 2, 2, 2],
  },
  c('TO', '+676',  'Tonga',                 'Tonga',                       '🇹🇴'),
  c('TT', '+1868', 'Trinidad and Tobago',   'Trinité-et-Tobago',           '🇹🇹'),
  c('TN', '+216',  'Tunisia',               'Tunisie',                     '🇹🇳'),
  c('TR', '+90',   'Turkey',                'Turquie',                     '🇹🇷'),
  c('TM', '+993',  'Turkmenistan',          'Turkménistan',                '🇹🇲'),
  c('TV', '+688',  'Tuvalu',                'Tuvalu',                      '🇹🇻'),
  c('UG', '+256',  'Uganda',                'Ouganda',                     '🇺🇬'),
  c('UA', '+380',  'Ukraine',               'Ukraine',                     '🇺🇦'),
  c('AE', '+971',  'United Arab Emirates',  'Émirats arabes unis',         '🇦🇪'),
  c('GB', '+44',   'United Kingdom',        'Royaume-Uni',                 '🇬🇧'),
  c('US', '+1',    'United States',         'États-Unis',                  '🇺🇸'),
  c('UY', '+598',  'Uruguay',               'Uruguay',                     '🇺🇾'),
  c('UZ', '+998',  'Uzbekistan',            'Ouzbékistan',                 '🇺🇿'),
  c('VU', '+678',  'Vanuatu',               'Vanuatu',                     '🇻🇺'),
  c('VA', '+379',  'Vatican City',          'Vatican',                     '🇻🇦'),
  c('VE', '+58',   'Venezuela',             'Venezuela',                   '🇻🇪'),
  c('VN', '+84',   'Vietnam',               'Viêt Nam',                    '🇻🇳'),
  c('YE', '+967',  'Yemen',                 'Yémen',                       '🇾🇪'),
  c('ZM', '+260',  'Zambia',                'Zambie',                      '🇿🇲'),
  c('ZW', '+263',  'Zimbabwe',              'Zimbabwe',                    '🇿🇼'),
]

export const PLATFORM_ISO_SET = new Set(['CM', 'CI', 'SN', 'TG', 'BJ'])
